# Generated by Django 6.0.1 on 2026-01-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='username',
            new_name='user',
        ),
    ]
