# Generated by Django 6.0.1 on 2026-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_username_urlshortener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
