# Generated by Django 6.0.1 on 2026-02-01 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_urlshortener_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
