# Generated by Django 6.0.1 on 2026-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_urlshortener_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
